package com.finki.budgetwisely.service.impl;

import com.finki.budgetwisely.model.RecurringTransaction;
import com.finki.budgetwisely.model.Transaction;
import com.finki.budgetwisely.model.enums.RecurrenceFrequency;
import com.finki.budgetwisely.repository.RecurringTransactionRepository;
import org.slf4j.Logger;
import org.slf4j.LoggerFactory;
import org.springframework.scheduling.annotation.Scheduled;
import org.springframework.stereotype.Service;
import org.springframework.transaction.annotation.Transactional;

import java.time.LocalDate;
import java.util.List;

@Service
public class RecurringTransactionScheduler {

    private static final Logger logger = LoggerFactory.getLogger(RecurringTransactionScheduler.class);

    private final RecurringTransactionRepository recurringTransactionRepository;
    private final TransactionServiceImpl transactionService;

    public RecurringTransactionScheduler(RecurringTransactionRepository recurringTransactionRepository,
                                         TransactionServiceImpl transactionService) {
        this.recurringTransactionRepository = recurringTransactionRepository;
        this.transactionService = transactionService;
    }

    // Run daily at 00:05 AM
    @Scheduled(cron = "0 5 0 * * ?")
    @Transactional
    public void processRecurringTransactions() {
        logger.info("Starting recurring transaction processing at {}", LocalDate.now());

        LocalDate today = LocalDate.now();
        List<RecurringTransaction> activeRecurrences =
                recurringTransactionRepository.findAllActiveForProcessing(today);

        logger.info("Found {} active recurring transactions to process", activeRecurrences.size());

        int processedCount = 0;
        int skippedCount = 0;

        for (RecurringTransaction recurring : activeRecurrences) {
            try {
                if (shouldGenerateTransaction(recurring, today)) {
                    generateTransaction(recurring, today);
                    recurring.setLastProcessedDate(today);
                    recurringTransactionRepository.save(recurring);
                    processedCount++;
                } else {
                    skippedCount++;
                }
            } catch (Exception e) {
                logger.error("Error processing recurring transaction ID: " + recurring.getId(), e);
            }
        }

        logger.info("Completed recurring transaction processing. Processed: {}, Skipped: {}",
                processedCount, skippedCount);
    }

    private boolean shouldGenerateTransaction(RecurringTransaction recurring, LocalDate today) {
        // Don't process if already processed today
        if (recurring.getLastProcessedDate() != null &&
                recurring.getLastProcessedDate().equals(today)) {
            logger.debug("Skipping recurring transaction ID {} - already processed today", recurring.getId());
            return false;
        }

        // Check if past end date
        if (recurring.getEndDate() != null && today.isAfter(recurring.getEndDate())) {
            logger.debug("Skipping recurring transaction ID {} - past end date", recurring.getId());
            return false;
        }

        // Check if before start date
        if (today.isBefore(recurring.getStartDate())) {
            logger.debug("Skipping recurring transaction ID {} - before start date", recurring.getId());
            return false;
        }

        // Check frequency
        boolean shouldGenerate = switch (recurring.getFrequency()) {
            case DAILY -> true;
            case WEEKLY -> today.getDayOfWeek().getValue() == recurring.getDayOfWeek();
            case MONTHLY -> today.getDayOfMonth() == recurring.getDayOfMonth();
            case YEARLY -> today.getDayOfMonth() == recurring.getDayOfMonth() &&
                    today.getMonthValue() == recurring.getStartDate().getMonthValue();
            case NONE -> false;
        };

        logger.debug("Recurring transaction ID {} - should generate: {}", recurring.getId(), shouldGenerate);
        return shouldGenerate;
    }

    private void generateTransaction(RecurringTransaction recurring, LocalDate date) {
        Transaction transaction = new Transaction();
        transaction.setName(recurring.getName());
        transaction.setCost(recurring.getCost());
        transaction.setDate(date.atStartOfDay());
        transaction.setType(recurring.getType());
        transaction.setCategory(recurring.getCategory());
        transaction.setAccount(recurring.getAccount());
        transaction.setRecurringTransaction(recurring);
        transaction.setIsAutoGenerated(true);

        transactionService.saveGeneratedTransaction(transaction);

        logger.info("Generated recurring transaction: '{}' for date: {} (Recurring ID: {})",
                recurring.getName(), date, recurring.getId());
    }
}
