import { Account } from "./Account";
import { Category } from "./Category";
import { TransactionType } from "./enum/TransactionType";
import { RecurringTransaction } from "./RecurringTransaction";

export interface Transaction{
    id : number;
    name : string;
    cost : number;
    date : Date;
    type : TransactionType; 
    category : Category;
    account : Account;
    recurringTransaction?: RecurringTransaction;
    isAutoGenerated?: boolean;
}